[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[language-server.typescript-language-server]
command = "npx"
args = ["typescript-language-server", "--stdio"]
